<?php

/**
 * @file
 * Database schema code for MySQL database servers.
 *
 * Portions of this file may be copyright by some authors of Drupal.
 *
 * Copyright (c) 2015, Regents of the University of Michigan.
 * All rights reserved. See LICENSE.txt for details.
 *
 */


/**
 * @addtogroup schemaapi
 * @{
 */

include_once DRUPAL_ROOT . '/includes/database/mysql/schema.inc';

class DatabaseSchema_primary_primary extends DatabaseSchema_mysql {}

